sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t91WfLEvukWrezKsGhC
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-secret: Ploqla4lhGAYdjyKhvWcnMLzg8O23a
    bucket-name: ruyiwei-web1
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx2fa1d0fe1f4282d5
    secret: 4274a3ca9eff20fcb29f80091570ea92
    mchid: 111
    mch-serial-no: 122
    private-key-file-path: key.pem
    api-v3-key: 123
    we-chat-pay-cert-file-path: pem
    notify-url: https://6effbf9f.r12.cpolar.top/notify/paySuccess
    refund-notify-url: https://6effbf9f.r12.cpolar.top/notify/refundSuccess

