sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t91WfLEvukWrezKsGhC
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-secret: Ploqla4lhGAYdjyKhvWcnMLzg8O23a
    bucket-name: ruyiwei-web1